/**
 * Chirp API
 * API for a social network with donations.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChirpApi);
  }
}(this, function(expect, ChirpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChirpApi.MessagesDonation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MessagesDonation', function() {
    it('should create an instance of MessagesDonation', function() {
      // uncomment below and update the code to test MessagesDonation
      //var instane = new ChirpApi.MessagesDonation();
      //expect(instance).to.be.a(ChirpApi.MessagesDonation);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new ChirpApi.MessagesDonation();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new ChirpApi.MessagesDonation();
      //expect(instance).to.be();
    });

    it('should have the property orgCode (base name: "orgCode")', function() {
      // uncomment below and update the code to test the property orgCode
      //var instane = new ChirpApi.MessagesDonation();
      //expect(instance).to.be();
    });

    it('should have the property orgName (base name: "orgName")', function() {
      // uncomment below and update the code to test the property orgName
      //var instane = new ChirpApi.MessagesDonation();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instane = new ChirpApi.MessagesDonation();
      //expect(instance).to.be();
    });

  });

}));
